spring.application.name=outbox-pattern-relay
server.port=8081
# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/outbox_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de Kafka
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Nombre del tópico de Kafka
kafka.topic.outbox=outbox-events-topic
